[package]
name = "rustproof"
version = "0.0.1"
authors = [
            "Matthew Slocum <arco000@gmail.com>",
            "Sami Sahli <samisahli@me.com>",
            "Vincent Schuster <>",
            "Matt O'Brien <>",
            "Michael Salter <>",
            "Bardley Rasmussen <>",
            "Drew Gohman <>"
          ]

[lib]
name = "rustproof"
path = "src/lib.rs"
plugin = true
