[package]
name = "rustproof"
version = "0.0.1"
authors = [
            "Matthew Slocum <arco000@gmail.com>",
            "Sami Sahli <samisahli@me.com>",
            "Vincent Schuster <vincent_schuster@outlook.com>",
            "Matthew O'Brien <matthewo@pdx.edu>",
            "Michael Salter <salterm@pdx.edu>",
            "Bradley Rasmussen <rasmbj@pdx.edu>",
            "Drew Gohman <dgohman@pdx.edu>"
          ]
<<<<<<< HEAD

build = "build.rs"
=======
#build = "build.rs"
>>>>>>> c470da0cce6a52618314ba0123cdc84db3aa4454

[build-dependencies]
lalrpop = "0.11.0"

[dependencies]
log = "0.3.6"
env_logger = "0.3.4"
lalrpop-util = "0.11.0"

[lib]
name = "rustproof"
path = "src/lib.rs"
plugin = true
