[package]
name = "rustproof"
version = "0.0.1"
authors = [
            "Matthew Slocum <arco000@gmail.com>",
            "Sami Sahli <samisahli@me.com>",
            "Vincent Schuster <>",
            "Matthew O'Brien <matthewo@pdx.edu>",
            "Michael Salter <salterm@pdx.edu>",
            "Bradley Rasmussen <>",
            "Drew Gohman <>"
          ]

[lib]
name = "rustproof"
path = "src/lib.rs"
plugin = true
